import { Demo } from "@/src/services/firestore"

export const demoCategories = [
  { id: "restaurant", name: "Restaurant", slug: "restaurant" },
  { id: "cafe", name: "Cafe", slug: "cafe" },
  { id: "gym", name: "Gym", slug: "gym" },
  { id: "salon", name: "Salon", slug: "salon" },
  { id: "clinic", name: "Clinic", slug: "clinic" },
  { id: "real-estate", name: "Real Estate", slug: "real-estate" },
  { id: "hotel", name: "Hotel", slug: "hotel" },
  { id: "portfolio", name: "Portfolio", slug: "portfolio" },
  { id: "agency", name: "Agency", slug: "agency" },
  { id: "saas", name: "SaaS", slug: "saas" },
  { id: "ecommerce", name: "Ecommerce", slug: "ecommerce" },
  { id: "education", name: "Education", slug: "education" },
  { id: "photography", name: "Photography", slug: "photography" },
  { id: "local-business", name: "Local Business", slug: "local-business" },
]

export const demos: Demo[] = [
  {
    id: "restaurant-bistro",
    name: "Bistro Modern",
    slug: "bistro-modern",
    category: "restaurant",
    description: "Elegant restaurant website with food photography and reservation CTA",
    price: 7999,
    thumbnail: "/demos/restaurant-bistro.jpg",
    screenshots: [
      "/demos/restaurant-bistro-1.jpg",
      "/demos/restaurant-bistro-2.jpg",
    ],
    features: [
      "Interactive menu grid",
      "Reservation booking form",
      "Location map integration",
      "Mobile ordering",
    ],
    tags: ["food", "reservation", "menu", "local"],
    livePreviewUrl: "https://bistro-modern.webforge.example",
    featured: true,
  },
  {
    id: "gym-premium",
    name: "Premium Gym",
    slug: "premium-gym",
    category: "gym",
    description: "Bold typography, pricing and membership CTA for fitness businesses",
    price: 14999,
    thumbnail: "/demos/gym-premium.jpg",
    screenshots: [
      "/demos/gym-premium-1.jpg",
      "/demos/gym-premium-2.jpg",
    ],
    features: [
      "Class schedule",
      "Trainer profiles",
      "Membership pricing tables",
      "Workout tracking",
    ],
    tags: ["fitness", "membership", "classes", "pricing"],
    livePreviewUrl: "https://premium-gym.webforge.example",
    featured: true,
  },
  {
    id: "salon-luxury",
    name: "Luxury Salon",
    slug: "luxury-salon",
    category: "salon",
    description: "Luxury editorial design and booking CTA for high-end salons",
    price: 12999,
    thumbnail: "/demos/salon-luxury.jpg",
    screenshots: [
      "/demos/salon-luxury-1.jpg",
      "/demos/salon-luxury-2.jpg",
    ],
    features: [
      "Appointment booking",
      "Service menu",
      "Team gallery",
      "Instagram feed",
    ],
    tags: ["beauty", "appointment", "styling", "editorial"],
    livePreviewUrl: "https://luxury-salon.webforge.example",
  },
  {
    id: "clinic-trust",
    name: "Medical Clinic",
    slug: "medical-clinic",
    category: "clinic",
    description: "Trust-focused medical layout and appointment CTA for healthcare practices",
    price: 15999,
    thumbnail: "/demos/clinic-trust.jpg",
    screenshots: [
      "/demos/clinic-trust-1.jpg",
      "/demos/clinic-trust-2.jpg",
    ],
    features: [
      "Doctor profiles",
      "Appointment scheduling",
      "Service categories",
      "Patient testimonials",
    ],
    tags: ["healthcare", "appointment", "medical", "trust"],
    livePreviewUrl: "https://medical-clinic.webforge.example",
  },
  {
    id: "real-estate-modern",
    name: "Modern Real Estate",
    slug: "modern-real-estate",
    category: "real-estate",
    description: "Property cards, filters and enquiry CTA for real estate agents",
    price: 18999,
    thumbnail: "/demos/real-estate-modern.jpg",
    screenshots: [
      "/demos/real-estate-modern-1.jpg",
      "/demos/real-estate-modern-2.jpg",
    ],
    features: [
      "Property listing grid",
      "Advanced search filters",
      "Mortgage calculator",
      "Agent contact",
    ],
    tags: ["property", "listings", "search", "investment"],
    livePreviewUrl: "https://modern-real-estate.webforge.example",
  },
  {
    id: "hotel-ocean",
    name: "Ocean Hotel",
    slug: "ocean-hotel",
    category: "hotel",
    description: "Coastal-inspired hotel website with booking and gallery",
    price: 22999,
    thumbnail: "/demos/hotel-ocean.jpg",
    screenshots: [
      "/demos/hotel-ocean-1.jpg",
      "/demos/hotel-ocean-2.jpg",
    ],
    features: [
      "Room gallery",
      "Booking engine",
      "Amenities grid",
      "Location highlights",
    ],
    tags: ["hospitality", "booking", "gallery", "rooms"],
    featured: true,
  },
  {
    id: "portfolio-agency",
    name: "Agency Case Studies",
    slug: "agency-case-studies",
    category: "agency",
    description: "Modern case-study driven layout for creative agencies",
    price: 24999,
    thumbnail: "/demos/agency-case-studies.jpg",
    screenshots: [
      "/demos/agency-case-studies-1.jpg",
      "/demos/agency-case-studies-2.jpg",
    ],
    features: [
      "Case study carousel",
      "Project filtering",
      "Team showcase",
      "Contact form",
    ],
    tags: ["agency", "case studies", "creative", "portfolio"],
  },
  {
    id: "saas-platform",
    name: "SaaS Platform",
    slug: "saas-platform",
    category: "saas",
    description: "Clean SaaS landing page with lead forms and analytics",
    price: 21999,
    thumbnail: "/demos/saas-platform.jpg",
    screenshots: [
      "/demos/saas-platform-1.jpg",
      "/demos/saas-platform-2.jpg",
    ],
    features: [
      "Feature grid",
      "Lead capture form",
      "Pricing tables",
      "Integration badges",
    ],
    tags: ["saas", "lead generation", "metrics", "growth"],
  },
  {
    id: "ecommerce-fashion",
    name: "Fashion Store",
    slug: "fashion-store",
    category: "ecommerce",
    description: "Stylish ecommerce with product grids and checkout flow",
    price: 27999,
    thumbnail: "/demos/ecommerce-fashion.jpg",
    screenshots: [
      "/demos/ecommerce-fashion-1.jpg",
      "/demos/ecommerce-fashion-2.jpg",
    ],
    features: [
      "Product catalog",
      "Filter by category",
      "Size selector",
      "Wishlist functionality",
    ],
    tags: ["shopping", "products", "catalog", "checkout"],
  },
  {
    id: "education-online",
    name: "Online Academy",
    slug: "online-academy",
    category: "education",
    description: "Course platform with module navigation and instructor profiles",
    price: 19999,
    thumbnail: "/demos/education-online.jpg",
    screenshots: [
      "/demos/education-online-1.jpg",
      "/demos/education-online-2.jpg",
    ],
    features: [
      "Course catalog",
      "Lesson progress",
      "Instructor bios",
      "Enrollment form",
    ],
    tags: ["courses", "learning", "education", "enrollment"],
  },
  {
    id: "photography-portfolio",
    name: "Photographer Portfolio",
    slug: "photographer-portfolio",
    category: "photography",
    description: "Minimalist portfolio with gallery filtering and contact",
    price: 16999,
    thumbnail: "/demos/photography-portfolio.jpg",
    screenshots: [
      "/demos/photography-portfolio-1.jpg",
      "/demos/photography-portfolio-2.jpg",
    ],
    features: [
      "Gallery grid",
      "Lightbox viewer",
      "Project categories",
      "Contact form",
    ],
    tags: ["portfolio", "gallery", "photography", "visual"],
  },
  {
    id: "local-bistro",
    name: "Local Business",
    slug: "local-business-v1",
    category: "local-business",
    description: "Simple local business website with contact and hours",
    price: 5999,
    thumbnail: "/demos/local-business.jpg",
    screenshots: [
      "/demos/local-business-1.jpg",
      "/demos/local-business-2.jpg",
    ],
    features: [
      "Contact form",
      "Hours of operation",
      "Location map",
      "Social links",
    ],
    tags: ["local", "business", "contact", "simple"],
  },
]